---
-name: Install And Start nginx
host: all #servers playbook can be executed/all services
become: root #if you need super_user to run this task

tasks:
  - name: Install nginx
  apt:
    name: nginx
    state: latest

  - name: Start nginx
    service:
      name: nginx
      state: started

  - name: Stop nginx
    service: 
      name: nginx
      state: stopped 

